---
create_user: "username here"
copy_local_key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"
sys_packages: [ 'software-properties-common', 'acl', 'curl', 'wget', 'vim', 'teleport']
new_hostname: "hostname here"
password: "hashed password here"
#ansible_ssh_private_key_file: ~/.ssh/"privatekeyfile"  #if not using default
