---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml
  tasks:

  # Version check for mailinabox

    - name: End the play for hosts that are not Ubuntu version 18.04
      fail:
        msg: Sorry this distribution {{ ansible_distribution }} is currently not supported for running this playbook.  Mailinabox is currently only compatible with Ubuntu 18.04 ONLY.
      when: ansible_distribution != 'Ubuntu' and ansible_distribution_version == '18.04'
      
  # Update system packages

    - name: Update system packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 3600
        state: latest

  # Install specified packages
 
    - name: Download teleport public key
      ansible.builtin.apt_key:
        url: https://deb.releases.teleport.dev/teleport-pubkey.asc
        state: present

    - name: Add teleport repo to apt      
      ansible.builtin.apt_repository:
        repo: deb https://deb.releases.teleport.dev/ stable main
        state: present
        install_python_apt: yes

    - name: Installing required system packages APT
      apt:
        name: "{{ sys_packages }}"
        state: latest

  # Set specified hostname

    - name: Set required hostname from specified
      command: "sudo {{ item }}"
      with_items:
        - hostnamectl set-hostname "{{ new_hostname }}"
        - hostnamectl set-hostname """{{ new_hostname }}""" --pretty
        - hostnamectl set-hostname "{{ new_hostname }}" --static
        - hostnamectl set-hostname "{{ new_hostname }}" --transient

    - name: Replace localhost entry to include specified hostname
      lineinfile:
        path: /etc/hosts
        search_string: '127.0.1.1'
        line: 127.0.1.1 {{ new_hostname }}
        owner: root
        group: root
        mode: '0644'

  # New user prerequisites

    - name: Remove login banner in skel for new users
      ansible.builtin.command: touch /etc/skel/.hushlogin

    - name: Check profile file exists
      stat:
        path: /etc/skel/.profile
      register: stat_result

    - name: Create profile file in skel for new users
      ansible.builtin.file:
        path: /etc/skel/.profile
        state: touch
      when: (not stat_result.stat.exists and ansible_distribution == 'Debian') or
            (not stat_result.stat.exists and ansible_distribution == 'Ubuntu') or
            (not stat_result.stat.exists and ansible_distribution == 'Linux Mint')

    - name: Add mystart script entry to skel profile for new users
      ansible.builtin.lineinfile:
        path: /etc/skel/.profile
        state: present
        line: 'source /opt/scripts/my_start/mystart.sh'
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' or ansible_distribution == 'Linux Mint'

    - name: Check zlogin file exists
      stat:
        path: /etc/skel/.zlogin
      register: stat_result
 
    - name: Create zlogin file in skel for new users
      ansible.builtin.file:
        path: /etc/skel/.zlogin
        state: touch
      when: not stat_result.stat.exists

    - name: Add mystart script entry to skel zlogin for new users
      ansible.builtin.lineinfile:
        path: /etc/skel/.zlogin
        state: present
        line: 'source /opt/scripts/my_start/mystart.sh'

    - name: Add mystart script entry to skel bashrc for new users
      ansible.builtin.lineinfile:
        path: /etc/skel/.bashrc
        state: present
        line: 'source /opt/scripts/my_start/mystart.sh'
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Fedora' or ansible_distribution == 'RedHat' or ansible_distribution == 'AlmaLinux'

  # New user(s) and ssh key setup

    - name: Create new user(s) with the specified name(s) and grant sudo privileges if specified
      ansible.builtin.user:
        name: "{{ create_user }}"
        password: "{{ password }}"
        state: present
        groups: sudo
        append: yes
        create_home: true
        shell: /bin/bash

    - name: Input ssh authorized key(s) for the new user(s)
      ansible.posix.authorized_key:
        user: "{{ create_user }}"
        state: present
        key: '{{ item }}'
      with_items:
        - "{{ copy_local_key }}"
      no_log: true

  # Start script set-up

    - name: Clone my_start script from git
      ansible.builtin.git:
        repo: https://github.com/gitorion/my_start.git
        dest: /opt/scripts/my_start/
        clone: yes
        version: main

    - name: Set ownership of cloned my_start script files
      ansible.builtin.file:
        path: /opt/scripts/my_start/
        owner: root
        group: sudo
        state: directory
        recurse: yes
        mode: u=rwx,g=rwx,o=rx

  # System reboot

    - name: Rebooting the system to complete updates
      reboot:

  # System security measures

    - name: Disable root login shell
      ansible.builtin.lineinfile:
        path: /etc/passwd
        state: present
        regexp: '^#?root:x:0:0:root:/root:'
        line: 'root:x:0:0:root:/root:/sbin/nologin'

    - name: Disable ssh root login
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'

    - name: Disable ssh password authentication
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'

    - name: Disable ssh login banner
      ansible.builtin.lineinfile:
        path: /etc/pam.d/sshd
        state: present
        regexp: '^#?session    optional     pam_motd.so  motd=/run/motd.dynamic'
        line: '#session    optional     pam_motd.so  motd=/run/motd.dynamic'

    - name: Diable ssh login banner update task
      ansible.builtin.lineinfile:
        path: /etc/pam.d/sshd
        state: present
        regexp: '^#?session    optional     pam_motd.so noupdate'
        line: '#session    optional     pam_motd.so noupdate'

    - name: Change banner permissions to prevent change
      ansible.builtin.file:
        path: /etc/update-motd.d/
        state: directory
        owner: root
        group: root
        mode: '0600'

  # Restart the sshd service to enable changes

    - name: Restart the sshd service
      command: sudo systemctl restart sshd