---
create_user: "insert username"
copy_local_key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"
sys_packages: [ 'acl', 'curl', 'wget', 'vim', 'ufw', 'zsh', 'git', 'teleport']
new_hostname: "insert hostname"
password: "insert hashed password"
#ansible_ssh_private_key_file: ~/.ssh/LightsailDefaultKey-eu-west-1 #if using lightsail instance
